name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
  release:
    types:
      - published
jobs:
  build_wheels:
    name: Build wheels [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.11
        os:
          - ubuntu-24.04

    steps:
      - uses: actions/checkout@master
      - run: git fetch --prune --unshallow

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pypa/build
        run: pip install build

      - name: Build wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy_PyPI:
    name: 📦 Deploy to PyPI
    runs-on: ubuntu-24.04
    needs: [build_wheels]
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
